import { Box, Text } from "@chakra-ui/react";
import FileUpload from "components/FileUpload";
import Head from "next/head";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p="2rem">
        <Text>Yo</Text>
        <FileUpload />
      </Box>
    </Box>
  );
}
